### ISSUE TITLE
Añadir Formulario de login

### ISSUE THREAD

**Issue by lizloera** [lizloera/webhotel#14]
utilizar flexbox 
añadir campos para pedir informacion del usuario basica(nombre, usuario, email, tel,)
asi como los datos del perro(nombre, raza, edad, complecion, observaciones, medida)
apegarse a los tonos manejados , rosa y naranja establecidos en la pagina principal , asi como los tipos de fuente

**Comment by ZzoldierzZ** [comment]
ya se creó el formulario y se habilito la opcion de registro.
